services:

  db_proxy_primary:
    container_name: db_proxy_primary
    image: 'mariadb:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '53u71l17135'
      MYSQL_DATABASE: 'proxy_primary_db'
      MYSQL_USER: 'se-utilities'
      MYSQL_PASSWORD: '53u71l17135'
    volumes:
      - ./data/mysql_proxy_primary:/var/lib/mysql
  
  db_proxy_secondary:
    container_name: db_proxy_secondary
    image: 'mariadb:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '53u71l17135'
      MYSQL_DATABASE: 'proxy_secondary_db'
      MYSQL_USER: 'se-utilities'
      MYSQL_PASSWORD: '53u71l17135'
    volumes:
      - ./data/mysql_proxy_secondary:/var/lib/mysql
  
  db_guacamole:
    container_name: db_guacamole
    image: 'mariadb:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '53u71l17135'
      MYSQL_DATABASE: 'guacamole_db'
      MYSQL_USER: 'se-utilities'
      MYSQL_PASSWORD: '53u71l17135'
    volumes:
      - ./init/mysql_guacamole:/docker-entrypoint-initdb.d
      - ./data/mysql_guacamole:/var/lib/mysql

  proxy:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '50001:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: 'db_proxy_primary'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: 'se-utilities'
      DB_MYSQL_PASSWORD: '53u71l17135'
      DB_MYSQL_NAME: 'proxy_primary_db'
    volumes:
      - ./data/nginx-proxy/data:/data
      - ./data/nginx-proxy/letsencrypt:/etc/letsencrypt
    depends_on:
      - db_proxy_primary


  rw_proxy:
    container_name: nginx-proxy-manager-secondary
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '50002:81'
      - '8443:443'
    environment:
      DB_MYSQL_HOST: 'db_proxy_secondary'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: 'se-utilities'
      DB_MYSQL_PASSWORD: '53u71l17135'
      DB_MYSQL_NAME: 'proxy_secondary_db'
    volumes:
      - ./data/nginx-proxy-secondary/data:/data
      - ./data/nginx-proxy-secondary/letsencrypt:/etc/letsencrypt
    depends_on:
      - db_proxy_secondary
    
  guacd:
    container_name: guacd
    image: guacamole/guacd
    restart: unless-stopped

  guacamole:
    container_name: guacamole
    image: 'guacamole/guacamole:latest'
    restart: unless-stopped
    ports:
      - '50003:8080'
    environment:
      GUACD_HOSTNAME: 'guacd'
      MYSQL_HOSTNAME: 'db_guacamole'
      MYSQL_DATABASE: 'guacamole_db'
      MYSQL_USER: 'se-utilities'
      MYSQL_PASSWORD: '53u71l17135'
    depends_on:
      - db_guacamole
      - guacd
    
  dbeaver:
    container_name: dbeaver
    image: 'dbeaver/cloudbeaver:latest'
    restart: unless-stopped
    ports:
      - '50004:8978'
    volumes:
      - ./data/cloudbeaver:/opt/cloudbeaver/workspace